product:
    namespace: brodagroupsoftware.com
    name: rmi.dataproduct
    description: RMI’s Utility Transition HubTM helps key stakeholders—regulators, investors, policymakers, advocates, and utilities—chart a path to an equitable and affordable energy transition
    tags: ["utilities", "emissions"]
    publisher: publisher.user@brodagroupsoftware.com
    endpoints:
        discovery: http://localhost:9999/discovery
        observability: http://localhost:9999/observability
        administration: http://localhost:9999/administration